version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: web
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - ./envs/django
      - ./envs/postgres
    ports:
      - "8000:8000"
    command: /start

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: reservation_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./envs/postgres
    ports:
      - "5432:5432"
