# Generated by Django 2.2.2 on 2019-06-17 16:57

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('elapsed_time', models.PositiveIntegerField(default=0)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None), size=None)),
                ('moves', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), size=None), size=None)),
                ('state', models.IntegerField(choices=[(0, 'new'), (1, 'won'), (2, 'lost'), (3, 'started'), (4, 'paused')], default=0)),
                ('name', models.CharField(max_length=100)),
                ('mines', models.PositiveIntegerField(default=0)),
                ('flags', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Game',
                'db_table': 'game',
            },
        ),
    ]
