# Generated by Django 2.2.2 on 2019-06-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('NEW', 'new'), ('WON', 'won'), ('LOST', 'lost'), ('STARTED', 'started'), ('PAUSED', 'paused')], default='NEW', max_length=25),
        ),
    ]
