# Generated by Django 2.2.2 on 2019-06-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_change_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_play',
            field=models.DateTimeField(null=True),
        ),
    ]
